[project]
name = "astr7500"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "astropy>=7.2.0",
    "notebook",
    "ipykernel",
    "scipy>=1.17.0",
    "matplotlib>=3.10.8",
]
